#!/usr/bin/env python3
"""Grade the board against the one it replaced, and fail loudly when it should.

WHY THIS EXISTS
    Every real defect this system has produced was found by a human noticing, or
    by an audit someone thought to ask for. Not one was caught by the system.

    On 2026-08-11 alone: a manufactured home published a $780,300 ARV built from
    a warehouse's assessor row; one county appraisal was stamped on 1,433 leads
    and drove $320,145,300 of max bids; a noon job's 1,064 resolved addresses
    were silently reverted by a concurrent writer; 6,426 cards showed a satellite
    photo of a place 1-2 miles from the property. Every one of those published
    successfully. Nothing errored. The tests were green.

    That is the actual gap — not coverage, not sources. A board that cannot tell
    when it has gone wrong is a board you have to audit by hand forever.

WHAT IT DOES
    Compares the REAL current board (streamed live via board_stream.
    iter_board_rows() — never the listings_slim.json.gz mobile derivative,
    which append_new_rows()/patch_existing_rows() leave stale between full
    writes; see _current()'s docstring) against the previously PUBLISHED one
    (the committed slim .gz in git, for MOVEMENT only — see _previous()), and
    reports two different things:

      INVARIANTS  — statements that must be true of any board we publish.
                    A breach exits non-zero. These are not thresholds or
                    heuristics; each one means a specific known defect is back.

      MOVEMENT    — how much changed since the last publish, per field. This
                    does not fail. It is the signal a human reads to notice
                    "why did 4,000 ARVs move when I only edited the CSS?".
                    Silent, unexplained movement is how all of the above got in.

WHY MOVEMENT IS REPORTED AND NOT ENFORCED
    A legitimate run moves a lot: a fresh scrape adds leads, a vision pass
    scores 12,000 of them, a valuation fix withdraws $72M of max bid on purpose.
    Thresholding that would either fire constantly (and be ignored, which is
    worse than nothing) or be set so loose it never fires. So movement is
    printed, loudly and comparably, for a human to sanity-check against what
    they believe they changed.

USAGE
    uv run python scripts/board_selfcheck.py            # vs the last commit
    uv run python scripts/board_selfcheck.py --json     # machine-readable
    uv run python scripts/board_selfcheck.py --against <git-ref>

    Exit 0 = every invariant held. Exit 1 = at least one breached.
"""
from __future__ import annotations

import argparse
import gzip
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
SLIM = "docs/listings_slim.json.gz"

#: Flags that mean the valuation itself is disputed. A lead carrying one of
#: these must not publish money derived from the ARV. Kept in sync with
#: valuation.grading.ARV_FLAGS_CONTRADICTED — imported rather than restated so a
#: rename cannot make this check silently vacuous, which is the exact failure
#: mode (a reader and a writer disagreeing) that produced five separate silent
#: defects in one day.
try:
    sys.path.insert(0, str(REPO / "src"))
    from foreclosure_scraper.valuation.grading import ARV_FLAGS_CONTRADICTED
    CONTRADICTED = frozenset(ARV_FLAGS_CONTRADICTED)
except Exception:  # noqa: BLE001 - the check must still run from a bare checkout
    CONTRADICTED = frozenset({
        "anchor_shared_across_parcels", "bid_proxy_arv", "arv_above_anchor",
        "arv_above_list_price", "arv_land_sqft_mismatch", "arv_proxy_above_ceiling",
        "arv_above_plausible_max", "arv_implies_implausible_roi",
    })

# The REAL current board, streamed one row at a time (memory-safe on the 8 GB
# Mac: ~290 MB peak RSS for the full 219k-row board, measured 2026-09-30) —
# never listings_slim.json.gz. That mobile derivative is only regenerated by a
# full write_artifact() call; append_new_rows()/patch_existing_rows()
# (2026-09-29, commits 3272b3c0/758d0bb5) are now the write path for most
# board landings and deliberately leave it stale (see their own docstrings,
# and web_artifact.py's SLIM-V1 block comment). Importing it here, rather than
# catching an ImportError at call time, means a bare checkout without the
# package fails loudly at startup instead of silently falling back to a stale
# read the way an earlier version of this script did.
from foreclosure_scraper import board_parts as _board_parts
from foreclosure_scraper.board_stream import iter_board_rows

MONEY_FIELDS = ("max_bid_70", "roi_pct", "estimated_profit", "wholesale_mao")


def _load_gz(raw: bytes) -> list:
    return json.loads(gzip.decompress(raw).decode("utf-8"))


def _current() -> list:
    """The real, currently published board — see the import comment above for
    why this is iter_board_rows() and not listings_slim.json.gz."""
    try:
        rows = list(iter_board_rows(DOCS / "listings.json.gz"))
    except _board_parts.BoardIntegrityError as exc:
        raise SystemExit(f"board payload is not intact — {exc}") from exc
    except FileNotFoundError as exc:
        # No manifest, no parts, and no legacy single listings.json.gz either: there is no
        # board here at all (a bare checkout, or docs/ pointed at an empty scratch dir).
        raise SystemExit(f"no board found under {DOCS} — nothing to check ({exc})") from exc
    if not rows:
        raise SystemExit("no board rows found under docs/ — nothing to check")
    return rows


def _previous(ref: str) -> list | None:
    """The board as of `ref`, for MOVEMENT only (never for invariants).

    Deliberately still listings_slim.json.gz, not the full board: the full
    board has not been one committed path since the 2026-09-21 payload split
    (docs/listings.json.gz is no longer written; it is N listings_part_NNN.json.gz
    files, and N changes between commits), so there is no single path a plain
    `git show <ref>:<path>` can read for it. The slim file is still committed
    whole at one stable path on every full write_artifact() run, which makes it
    the only cheap way to diff "what did the board look like at a past commit"
    without checking out that commit's entire part set. It undercounts a board
    published only through append_new_rows()/patch_existing_rows() since the
    last full write (see _current()'s comment) — MOVEMENT already reports "new"
    for anything it does not recognize, so that shows up as new leads, not as a
    hidden gap."""
    r = subprocess.run(["git", "show", f"{ref}:{SLIM}"],
                       cwd=REPO, capture_output=True)
    if r.returncode != 0 or not r.stdout:
        return None
    try:
        return _load_gz(r.stdout)
    except Exception:  # noqa: BLE001
        return None


def _calc(rec) -> dict:
    return ((rec or {}).get("raw") or {}).get("calc") or {}


def _identifier(rec) -> str | None:
    """A value that genuinely distinguishes ONE property, or None.

    Returns None deliberately and often. The first version of this used
    address+case+county+state+source with empty-string fallbacks, and reported
    8,241 duplicates on a board that has almost none:

      7,901 of them were leads where BOTH address and case_number are empty, so
            every address-less lead in a county collapsed onto one key;
        644 were parcels sharing a road name with no house number — "SR 1135",
            "HWY 226", "OFF PARKER PADGETT RD" in McDowell — which are distinct
            properties that simply have no street number to tell them apart.

    Neither is a duplicate. A guard that fires on 8,241 good leads is worse than
    no guard, because the next person deletes it and takes the real check with
    it.

    Two further identifiers were tried and rejected on the evidence:

      source_url — identifies the SOURCE DOCUMENT, not the property. 80 leads
        share one Lincoln County delinquent-tax PDF; 8 share one Asheville
        permits endpoint. Every one is a different house.
      case_number — one foreclosure case routinely covers several parcels, so a
        shared case is normal, not a collision.

    What is left is what actually names a property: the county's own parcel id,
    or a street address carrying a house number. When a lead has neither, this
    returns None and the lead is excluded from the duplicate count rather than
    guessed at.
    """
    r = rec or {}
    pid = str(r.get("parcel_id") or "").strip()
    if pid:
        return f"parcel:{(r.get('county') or '').lower()}:{pid.lower()}"
    addr = str(r.get("street_address") or "").strip()
    parts = addr.split()
    if parts and any(ch.isdigit() for ch in parts[0]):
        return f"addr:{(r.get('county') or '').lower()}:{addr.lower()}"
    return None


def _key(rec) -> str:
    """Stable identity for MATCHING a lead across two publishes.

    Falls back to a composite so every lead gets compared; unlike _identifier
    this is allowed to be imprecise, because a wrong match here only mislabels a
    lead as changed rather than asserting a defect.
    """
    return _identifier(rec) or "|".join(
        str((rec or {}).get(f) or "") for f in
        ("street_address", "case_number", "county", "state", "source"))


#: A parcel/address key carried by this many OR MORE distinct street addresses is not
#: describing one property -- it is a fused or placeholder identifier in the SOURCE data
#: (a master-tract PIN a subdivision's lots all cite before the county assigns individual
#: ones, a missing-parcel sentinel, a scraper that fell back to a body of water or a lot
#: description in the parcel field). Same threshold `dedupe.suspicious_parcel_keys()`
#: already uses for the identical reason, restated here rather than imported: importing
#: it would mean building a `Listing` per board row just to reach `dedupe_key()`, which is
#: the whole-board materialization this script's read of listings_slim.json.gz already
#: avoids paying twice for.
#:
#: WHY THIS EXISTS (2026-09-29 audit of a 7,536 "duplicate" reading). Grouping the board's
#: 217k rows by `_identifier()` found 1,303 groups with 2+ rows. The 20 LARGEST groups
#: alone (out of 1,303) covered 5,623 of the 8,839 rows in duplicate groups -- three
#: quarters of the count -- and every one of them was this exact phenomenon, not a real
#: duplicate:
#:   parcel:lincoln:3633940779       1,618 rows, 1,580 from counties_nc.lincoln_vacant,
#:                                   each a DIFFERENT real street (SIGMON ST, W CHILDS ST,
#:                                   POWER LINE RD, MISTY DAWN LN, GAMBLE DR, ...) -- a
#:                                   placeholder/garbage parcel_id the scraper emits when it
#:                                   has no real one.
#:   parcel:pender:3208-90-5620-0000   216 rows -- the EXACT case dedupe.py's own
#:                                   suspicious_parcel_keys() docstring names: one
#:                                   master-tract PIN a subdivision's lots all cite, 216
#:                                   distinct addresses, already known and deliberately kept
#:                                   UNMERGED by dedupe()'s house-number guard so the merge
#:                                   does not silently delete 215 real properties.
#:   parcel:transylvania:escrow :    163 rows sharing the literal string "escrow :" as a
#:                                   "parcel id".
#:   parcel:carteret:bogue sound      71 rows sharing "bogue sound" (a body of water).
#: `dedupe()` already refuses to merge any of these (that is WHY they are still separate
#: rows); counting them as "duplicates" here was this check's own false alarm, not a
#: rediscovery of a defect dedupe() missed. Below the threshold is where the real signal
#: lives: 2-3 rows sharing a key with the SAME or an absent house number are what an
#: undedup'd cross-source landing (measured example: `counties_generic.arcgis_distress.
#: buncombe_unpaid_bills` storing the tax bill's MAILING address in `street_address` --
#: documented in `scripts/resolve_parcel_from_address.py`'s DENY_SOURCES, "23%: bill
#: mailing address" -- against `counties.multi_year_delinquent_tax`'s situs address, same
#: parcel, 206+ pairs) actually looks like, and this check still catches those.
#: FIXED AT THE SOURCE 2026-09-29 (arcgis_distress_layers.py now builds situs from
#: house_num/street_name/street_type, same as multi_year_delinquent_tax, and keeps the
#: mailing address in raw["owner_mailing"] instead): NEW rows from this source will not
#: reproduce this pair. The ~206+19 rows already on the board from before the fix are
#: NOT backfilled by that change and still need the separate load_board()+dedupe()+
#: write_artifact() normalize pass already flagged as follow-up work.
FUSION_THRESHOLD = 4


def invariants(board: list) -> list[dict]:
    """Each entry is a statement that must be true. Breach = a known defect is back."""
    out = []

    contra = [r for r in board if any(f in (_calc(r).get("arv_flags") or [])
                                      for f in CONTRADICTED)]
    for field in MONEY_FIELDS:
        bad = [r for r in contra if _calc(r).get(field)]
        out.append({
            "name": f"no {field} on a contradicted ARV",
            "count": len(bad), "must_be": 0, "ok": not bad,
            "why": "the valuation disputes its own number; money derived from it "
                   "is a bid instruction built on a figure we refused to stand behind",
        })

    bad = [r for r in contra if _calc(r).get("deal_status")]
    out.append({"name": "no deal verdict on a contradicted ARV", "count": len(bad),
                "must_be": 0, "ok": not bad,
                "why": "a green GREAT beside a red do-not-bid warning is how this "
                       "shipped before"})

    bad = [r for r in contra if (((r.get("raw") or {}).get("equity") or {}).get("value"))]
    out.append({"name": "no equity on a contradicted ARV", "count": len(bad),
                "must_be": 0, "ok": not bad,
                "why": "equity is ARV minus payoff; on a disputed ARV it is the same "
                       "disputed number wearing a different label, and it feeds the "
                       "HOT/WARM ranking"})

    big = [r for r in board if (_calc(r).get("arv_expected") or 0) > 2_000_000]
    bad = [r for r in big if _calc(r).get("max_bid_70")]
    out.append({"name": "no max bid on an ARV over $2M", "count": len(bad),
                "must_be": 0, "ok": not bad,
                "why": "no comparable property in these counties has fetched that; "
                       "the grader already refuses to letter-grade them"})
    bad = [r for r in big if not _calc(r).get("arv_flags")]
    out.append({"name": "every ARV over $2M carries a flag", "count": len(bad),
                "must_be": 0, "ok": not bad,
                "why": "an unflagged $2M+ ARV is indistinguishable from a real one"})

    groups: dict[str, list] = {}
    for r in board:
        ident = _identifier(r)
        if ident:
            groups.setdefault(ident, []).append(r)
    identified = sum(len(v) for v in groups.values())
    unidentifiable = len(board) - identified

    dupes = 0
    fused_keys = 0
    fused_rows = 0
    for rows in groups.values():
        if len(rows) < 2:
            continue
        addrs = {str(r.get("street_address") or "").strip().lower() for r in rows}
        addrs.discard("")
        if len(addrs) >= FUSION_THRESHOLD:
            # Many DISTINCT real addresses under one key: the key is fused/placeholder in
            # the source data, not one property landed twice. dedupe() already refuses to
            # merge these (see FUSION_THRESHOLD's comment) -- reported below, not counted
            # as a breach.
            fused_keys += 1
            fused_rows += len(rows)
            continue
        dupes += len(rows) - 1

    entry = {"name": "no duplicate identifiable properties", "count": dupes,
             "must_be": 0, "ok": dupes == 0,
             "why": "two rows for one property double-count it in every total "
                    f"and split its enrichment ({unidentifiable:,} leads carry no "
                    "parcel/case/url/numbered-address and are excluded — they "
                    "cannot be judged either way)"}
    if fused_keys:
        entry["fused_keys"] = fused_keys
        entry["fused_rows"] = fused_rows
        entry["fused_note"] = (
            f"{fused_keys:,} parcel/address key(s) shared by {FUSION_THRESHOLD}+ distinct "
            f"street addresses ({fused_rows:,} rows) excluded from the count above as "
            "fused/placeholder identifiers, not duplicates -- see FUSION_THRESHOLD's "
            "comment")
    out.append(entry)
    return out


def movement(cur: list, prev: list) -> dict:
    """What changed since the last publish. Reported, never enforced."""
    pi = {_key(r): r for r in prev}
    matched = gained = lost = 0
    moved: dict[str, int] = {f: 0 for f in ("arv_expected",) + MONEY_FIELDS}
    big_moves = []
    for r in cur:
        p = pi.get(_key(r))
        if p is None:
            gained += 1
            continue
        matched += 1
        c, pc = _calc(r), _calc(p)
        for f in moved:
            a, b = c.get(f), pc.get(f)
            if a != b:
                moved[f] += 1
                if f == "arv_expected" and a and b:
                    try:
                        if abs(a - b) / max(b, 1) >= 1.0:
                            big_moves.append((abs(a - b), r.get("street_address"), b, a))
                    except Exception:  # noqa: BLE001
                        pass
    ck = {_key(r) for r in cur}
    lost = sum(1 for r in prev if _key(r) not in ck)
    # Sort on the delta ONLY. A bare reverse=True falls through to comparing the
    # next tuple element when deltas tie, and street_address is None on hundreds
    # of leads, which raises str < NoneType and takes down the whole check.
    big_moves.sort(key=lambda t: t[0], reverse=True)
    return {
        "prev_count": len(prev), "curr_count": len(cur),
        "matched": matched, "new": gained, "dropped": lost,
        "changed": moved,
        "largest_arv_moves": [
            {"address": a, "from": b, "to": c2} for _, a, b, c2 in big_moves[:10]
        ],
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--against", default="HEAD",
                    help="git ref holding the board to compare against (default HEAD)")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    cur = _current()
    inv = invariants(cur)
    prev = _previous(args.against)
    mv = movement(cur, prev) if prev else None
    breached = [i for i in inv if not i["ok"]]

    if args.json:
        print(json.dumps({"invariants": inv, "movement": mv,
                          "breached": len(breached)}, indent=1, default=str))
        return 1 if breached else 0

    print(f"BOARD SELF-CHECK — {len(cur):,} leads\n")
    print("INVARIANTS (a breach means a known defect is back)")
    for i in inv:
        mark = "ok " if i["ok"] else "FAIL"
        print(f"  [{mark}] {i['name']:44} {i['count']:>6,} (must be {i['must_be']})")
        if not i["ok"]:
            print(f"         why it matters: {i['why']}")
        if i.get("fused_keys"):
            print(f"         excluded as fused/placeholder: {i['fused_note']}")

    if mv is None:
        print(f"\nMOVEMENT: no previous board at {args.against} — nothing to compare.")
    else:
        print(f"\nMOVEMENT vs {args.against}")
        print(f"  leads      {mv['prev_count']:,} -> {mv['curr_count']:,}"
              f"   (+{mv['new']:,} new / -{mv['dropped']:,} dropped / {mv['matched']:,} matched)")
        for f, n in mv["changed"].items():
            pct = (n / mv["matched"] * 100) if mv["matched"] else 0
            print(f"  {f:20} changed on {n:>6,} matched leads  ({pct:4.1f}%)")
        if mv["largest_arv_moves"]:
            print("\n  largest ARV moves (>=2x) — check these against what you changed:")
            for m in mv["largest_arv_moves"][:6]:
                print(f"    {str(m['address'])[:34]:36} "
                      f"{(m['from'] or 0):>12,.0f} -> {(m['to'] or 0):>12,.0f}")
        print("\n  Movement never fails this check. A real run moves a lot: a scrape adds")
        print("  leads, a vision pass scores thousands, a valuation fix withdraws money on")
        print("  purpose. It is printed so a human can ask 'why did that move when I only")
        print("  changed the CSS?' — which is the question nothing was asking before.")

    if breached:
        print(f"\n{len(breached)} INVARIANT(S) BREACHED — do not publish this board.")
        return 1
    print("\nAll invariants held.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
