#!/usr/bin/env python3
"""Build src/foreclosure_scraper/_zip_to_county.py: the NC/SC ZIP codes that sit in ONE county,
from offline evidence only (no network).

WHY (audit 2026-10-09, drops_lineage). main.run drops a national / REO row it cannot place in a
county (orchestrator.drop_countyless_national, 3,767 rows on 2026-10-08). The city gazetteer
(drop_audit.fill_county_from_city) places 395 of the 906 countyless national rows of that day's
hand-off; the rest carry an NC/SC ZIP. This table lets the same step place them by ZIP.

EVIDENCE: exactly scripts/backfill_missing_county.py's (Evidence.build_from_caches + the board
cross-check + Evidence._table): owner-occupied parcels in every county parcel cache give
(ZIP, county) pairs; a ZIP is kept only when one county holds >= 98% of at least 5 cache rows and
the published board's own rows for that ZIP agree (or, the board silent, the cache has 20+ rows),
or the board alone is overwhelming (10+ rows, 99%) with no cache row at all. A ZIP that spans
counties is left out, never guessed.

    uv run python scripts/build_zip_county_table.py            # writes the module, prints counts
    uv run python scripts/build_zip_county_table.py --dry-run  # counts only
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _dq_common import REPO, iter_rows  # noqa: E402
from backfill_missing_county import Evidence  # noqa: E402

OUT = REPO / "src" / "foreclosure_scraper" / "_zip_to_county.py"


def build() -> tuple[dict[tuple[str, str], str], Counter]:
    ev = Evidence()
    ev.build_from_caches()
    for rec in iter_rows():
        ev.add_board_row(rec.get("state"), rec.get("county"), rec.get("zip_code"), rec.get("city"))
    table: dict[tuple[str, str], str] = {}
    notes: Counter = Counter()
    for key in sorted(set(ev.cache_zip) | set(ev.board_zip)):
        county, note = ev._table(ev.cache_zip, ev.board_zip, key)
        notes[note] += 1
        if county:
            st, z = key.split("|", 1)
            table[(st, z)] = county
    for con_list in ev.caches.values():
        for _c, con in con_list:
            con.close()
    return table, notes


def render(table: dict[tuple[str, str], str], notes: Counter) -> str:
    lines = [
        '"""NC/SC ZIP code -> the one county it lies in. GENERATED by scripts/build_zip_county_table.py',
        f"({date.today().isoformat()}) from the county parcel caches and the published board; do not edit by hand.",
        "",
        "A ZIP that spans counties is absent. Evidence per ZIP (scripts/backfill_missing_county.py rules):",
        "  " + ", ".join(f"{k} {v}" for k, v in sorted(notes.items())),
        '"""',
        "from __future__ import annotations",
        "",
        "ZIP_COUNTY: dict[tuple[str, str], str] = {",
    ]
    lines += [f'    ("{st}", "{z}"): "{c}",' for (st, z), c in sorted(table.items())]
    lines += [
        "}",
        "",
        "",
        "def county_for_zip(zip_code, state) -> str | None:",
        '    """The county of an NC/SC ZIP that lies in one county, else None."""',
        "    z = str(zip_code or \"\").strip()[:5]",
        "    st = str(state or \"\").strip().upper()",
        "    return ZIP_COUNTY.get((st, z)) if len(z) == 5 and z.isdigit() else None",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    table, notes = build()
    by_state = Counter(st for st, _ in table)
    print(f"ZIPs placed: {len(table)} ({dict(by_state)}); evidence: {dict(notes)}")
    if not a.dry_run:
        OUT.write_text(render(table, notes))
        print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
